# Base configs
# baseurl: "https://photography.rampatra.com"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photos by Ben"
subtitle: "A small library"
header:
 title: "Photos"
 subtitle: "By Ben"
footer:
 name: "About"
 bio: "In my spare time, I enjoy learning about photography. This site is a collection of some of the things I've shot over the years. All images are royalty-free."
 github: "Check out my <a href=\"https://datsko.dev\">personal site</a> if you'd like to get in contact with me. <br><br>Inspired by <a href=\"https://github.com/ramswaroop/photography\">Ram Patra</a>."
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'

